export const CONSTRAINT_HELP_CODES = [
    'STAFF_COUNT_BY_SHIFT',
    'CORE_MAX_CONTINUOUS_WORK',
    'MIN_OFF_AFTER_CONSECUTIVE_WORK',
    'AVOID_ISOLATED_WORK_DAY',
    'AVOID_ISOLATED_OFF_DAY',
    'CORE_MIN_NIGHT_INTERVAL',
    'CORE_MAX_CONTINUOUS_NIGHT',
    'CORE_MIN_CONTINUOUS_NIGHT',
    'CORE_MIN_OFF_AFTER_NIGHT',
    'FORBID_N_THEN_D',
    'FORBID_N_THEN_E',
    'FORBID_E_THEN_D',
    'FORBID_E_THEN_N',
    'CORE_EXCLUDE_NIGHT_BEFORE_REQ_OFF',
    'NURSE_MAX_WEEKEND_HOLIDAY_SHIFTS',
    'NURSE_FORBID_WEEKEND',
    'NURSE_PREFER_SHIFT',
    'NURSE_AVOID_SHIFT',
    'NURSE_PAIR_NOT_SAME_SHIFT',
    'NURSE_PAIR_PREFER_SAME_SHIFT',
    'TWO_SHIFT_NIGHT_THEN_CONTINUATION',
    'TWO_SHIFT_NIGHT_CONTINUATION_AFTER_MIN_OFF',
    'TWO_SHIFT_NIGHT_PAIR_MIN_OFF',
    'MAX_MONTHLY_NIGHT_COUNT',
    'MIXED_ROTATION_PARTICIPATION',
    'MIXED_DAILY_COMPOSITION',
    'TWO_SHIFT_DAILY_LINES',
    'TWO_SHIFT_ASSIGNMENT_COUNT',
    'TIME_WINDOW_STAFF_COUNT',
    'MIN_REST_BETWEEN_SHIFTS',
    'MAX_WORK_MINUTES_BY_PERIOD',
    'MIXED_SHIFT_WORKLOAD_BALANCE',
    // These aliases can still appear in an existing saved schedule.
    'MAX_CONSECUTIVE_WORK_DAYS',
    'OFF_AFTER_CONSECUTIVE_WORK',
] as const;

const CONSTRAINT_HELP_CODE_SET = new Set<string>(CONSTRAINT_HELP_CODES);

export function hasConstraintHelp(templateCode: string) {
    return CONSTRAINT_HELP_CODE_SET.has(templateCode);
}
