name: Vitest Coverage Report

on:
  workflow_run:
    workflows: ['Vitest Unit Test']
    types:
      - completed

jobs:
  report:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: vitest-coverage
          path: apps/app/coverage
      - name: Comment coverage on pull request
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./apps/app
